"use client"
import { Inter,Outfit } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import {UserMembershipContext} from './_context/UserMembershipContext'
import { useEffect, useState } from 'react'
import { AptabaseProvider } from '@aptabase/react'
const inter = Outfit({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [userMembership,setUserMembership]=useState(false);


   useEffect(()=>{
    runOneSignal();
  },[])
  const runOneSignal=async()=>{
  
    // await OneSignal.init({ appId: '48bd7190-9366-4078-8ea9-6c2fcfa80703', allowLocalhostAsSecureOrigin: true});
    // OneSignal.Slidedown.promptPush();
    window.OneSignalDeferred = window.OneSignalDeferred || [];
OneSignalDeferred.push(function(OneSignal) {
  OneSignal.init({
    appId: "48bd7190-9366-4078-8ea9-6c2fcfa80703",
    safari_web_id: "web.onesignal.auto.69735df3-8f8c-40d7-a01f-205a16828de8",
    allowLocalhostAsSecureOrigin: true,
    notifyButton: {
      enable: true,
    },
  });
});
  }
  return (
    <ClerkProvider>
      <UserMembershipContext.Provider 
      value={{userMembership,setUserMembership}}>
    <html lang="en">
    <head>
      
      <script async src={"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client="+process.env.NEXT_PUBLIC_GOOGLE_ADS_KEY}
     crossorigin="anonymous"></script>
          {/* Add the OneSignal SDK script */}
          {/* <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async /> */}
        </head>
      <body className={inter.className}>
      <AptabaseProvider appKey="A-US-6917308331">
        {children}
        </AptabaseProvider>
        </body>
    </html>
    </UserMembershipContext.Provider>
    </ClerkProvider>
  )
}
